creation_rules:
  - path_regex: clusters/eks/.*\.yaml$
    age: age15x8awj9hyfhfmsvun0y7sc09xe7kcmdq30hevdh79np346377pzsxdge45
  - path_regex: clusters/gke/.*\.yaml$
    age: age15x8awj9hyfhfmsvun0y7sc09xe7kcmdq30hevdh79np346377pzsxdge45
