apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: external-dns
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      registry: registry.k8s.io
      repository: external-dns/external-dns
      tag: v0.20.0
    provider: aws
    aws:
      zoneType: public
    txtOwnerId: pdvd-eks
    serviceAccount:
      create: true
      name: external-dns
      annotations:
        # Note: If your AWS Account ID/Region differs, grab the exact ARN from your `terraform output`
        eks.amazonaws.com/role-arn: arn:aws:iam::754991274490:role/pdvd-eks-external-dns